on:
  push:
    branches: main
    tags:
      - '*'
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.10.3'
          cabal-version: '3.2'
      - name: Build - Install dependencies
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cabal update
          cabal build --only-dependencies --enable-tests --enable-benchmarks
      - name: Build - build application
        if: startsWith(github.ref, 'refs/tags/')
        run: cabal build --enable-tests --enable-benchmarks
      - name: Create release
        if: startsWith (github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: Lamtask/dist-newstyle/x86_64-Linux/ghc-*/Lamtask-*/x/Lamtask/build/Lamtask/Lamtask
          asset_name: Lamtask (Linux)
          asset_content_type: application/octet-stream
        
